name: "Bug Report"
description: Report an issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        *Thank you for taking your time to create a bug report. Please search open/closed issues before submitting, as the issue may have already been reported/addressed.*

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us how in the description. Thanks 🙏
      placeholder: Bug description
    validations:
      required: true

  - type: input
    id: components-affected
    attributes:
      label: Affected component(s)
      description: Which components are affected?
      placeholder: Button, Checkbox...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: Environment
      description: Information about your environment, such as operating system, browser version, and any relevant software versions.
      value: |
        - OS:
        - Browser:
        - Npm/Node:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Console/server logs around the time this bug occurred.
      render: bash