name: "Feature Request"
description: Request a new feature to improve Motif UI
labels: ['new feature']
body:
  - type: markdown
    attributes:
      value: |
        *Thank you for taking your time to create a feature request. Please search open/closed issues before submitting, as the issue may have already been reported/addressed.*

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your request
      placeholder: 'I think this feature would be great because...'
      value: 'Describe your feature request...'
    validations:
      required: true

  - type: input
    id: components-affected
    attributes:
      label: Related component(s)
      description: Is this feature relevant to any of the already existing components?
      placeholder: Button, Checkbox...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow the [Contribution Guide](https://github.com/motif-ui/demo-repository/blob/main/.github/CONTRIBUTING.md).
      options:
        - label: Accept
          required: true