#!/usr/bin/env bash

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [[ ! $branch_name =~ ^(bugfix|hotfix|test|feature)/EDKUI-[0-9]+/[a-zA-Z0-9_-]+$ ]]; then
  echo "❌ Invalid branch name: $branch_name"
  echo "Branch name must follow: bugfix|hotfix|test|feature/EDKUI-###/your-description"
  exit 1
fi

echo "✅ Branch name is valid. Push allowed."